apiVersion: apps/v1
kind: Deployment
metadata:
  name: victim-app
  labels:
    app: victim-app
spec:
  replicas: 2 # Wir starten direkt zwei Instanzen für Ausfallsicherheit
  selector:
    matchLabels:
      app: victim-app
  template:
    metadata:
      labels:
        app: victim-app
    spec:
      containers:
      - name: victim-app
        image: victim-app:v1
        imagePullPolicy: Never # WICHTIG: Sagt K8s, dass es unser lokales Image nutzen soll
        ports:
        - containerPort: 8080
        
        # Kubernetes prüft hiermit, ob die App bereit für Traffic ist
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
          
        # Kubernetes prüft hiermit, ob die App abgestürzt ist (Basis-Self-Healing)
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5